-- Généré par scripts/gen_seed.py. Ajoutez vos e-mails dans members avant (voir SETUP.md).
begin;
insert into rooms (id, name, sort) values ('maison', 'Toute la maison', 0);
insert into rooms (id, name, sort) values ('ch-liam', 'Chambre Liam', 1);
insert into rooms (id, name, sort) values ('ch-maceo', 'Chambre Maceo', 2);
insert into rooms (id, name, sort) values ('ch-solal', 'Chambre Solal', 3);
insert into rooms (id, name, sort) values ('ch-parents', 'Notre chambre', 4);
insert into rooms (id, name, sort) values ('ch-malik', 'Chambre Malik', 5);
insert into rooms (id, name, sort) values ('bureau', 'Bureau', 6);
insert into rooms (id, name, sort) values ('sdb-parents', 'Notre salle de bain', 7);
insert into rooms (id, name, sort) values ('sdb-enfants', 'SDB enfants + Malik', 8);
insert into rooms (id, name, sort) values ('salon', 'Salon / cuisine', 9);
insert into rooms (id, name, sort) values ('couloirs', 'Couloirs', 10);
insert into rooms (id, name, sort) values ('toit', 'Toit', 11);
insert into rooms (id, name, sort) values ('aile', 'Autre aile', 12);
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('enduit-rd', 'Enduit chaux : se documenter sur les recettes et dosages', 'Enduit chaux', 'test', 'haute', 120, 'Une seule recherche pour toute la maison (chambres, bureau, salon).', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('enduit-rd', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('enduit-essais', 'Enduit chaux : faire des essais sur panneaux', 'Enduit chaux', 'test', 'haute', 240, 'Noter chaque essai dans le carnet : recette, photo, verdict.', array['enduit-rd']::text[]);
insert into task_rooms (task_id, room_id) values ('enduit-essais', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('lum-dec', 'Éclairage : spots encastrés ou abat-jour ?', 'Électricité & lumières', 'decision', 'haute', 60, 'Bloque les saignées, donc l''enduit.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('lum-dec', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('termites-dec', 'Termites : choisir le produit et la méthode', 'Termites', 'decision', 'haute', 60, 'A faire avant toute peinture ou vernis sur le bois.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('termites-dec', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('turquoise-dec', 'Choisir le turquoise (teinte, type de peinture)', 'Portes & fenêtres', 'decision', 'normale', 45, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('turquoise-dec', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('rideaux-dec', 'Choisir les rideaux', 'Rideaux', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('rideaux-dec', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('ventilo-dec', 'Trouver la technique pour poser des ventilateurs', 'Ventilation', 'decision', 'normale', 90, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('ventilo-dec', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('solaire', 'Isoler le bruit du solaire : fermer le petit réduit', 'Bruit solaire', 'travaux', 'urgente', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('solaire', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('wc-visiteurs', 'Fermer les toilettes visiteurs (monter un mur)', 'Bruit solaire', 'travaux', 'haute', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('wc-visiteurs', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('porte-entree', 'Régler la porte d''entrée', 'Portes & fenêtres', 'travaux', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('porte-entree', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('penderie', 'Faire le(s) meuble(s) de penderie', 'Mobilier', 'travaux', 'normale', 960, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('penderie', 'maison');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('termites', 'Traitement termites', 'Termites', 'travaux', 'haute', 60, 'Salon : la fenêtre.', array['termites-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('termites', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('termites', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('termites', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('termites', 'bureau');
insert into task_rooms (task_id, room_id) values ('termites', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('termites', 'sdb-enfants');
insert into task_rooms (task_id, room_id) values ('termites', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('toit', 'Traiter le haut du toit (termites)', 'Termites', 'travaux', 'haute', 240, '', array['termites-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('toit', 'toit');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('saignees', 'Saigner les murs et passer les fils', 'Électricité & lumières', 'travaux', 'normale', 240, 'Avant l''enduit, sinon on casse l''enduit neuf.', array['lum-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('saignees', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('saignees', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('saignees', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('saignees', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('plafonds', 'Peindre le plafond', 'Peinture', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('plafonds', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('plafonds', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('plafonds', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('plafonds', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('boiseries', 'Peindre les boiseries', 'Peinture', 'travaux', 'normale', 180, '', array['termites']::text[]);
insert into task_rooms (task_id, room_id) values ('boiseries', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('boiseries', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('boiseries', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('boiseries', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('enduit', 'Appliquer l''enduit chaux', 'Enduit chaux', 'travaux', 'normale', 480, '', array['enduit-essais','saignees','plafonds']::text[]);
insert into task_rooms (task_id, room_id) values ('enduit', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('enduit', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('enduit', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('enduit', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('fenetres-turq', 'Peindre les fenêtres en turquoise', 'Portes & fenêtres', 'travaux', 'normale', 240, '', array['turquoise-dec','termites']::text[]);
insert into task_rooms (task_id, room_id) values ('fenetres-turq', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('fenetres-turq', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('fenetres-turq', 'ch-solal');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('portes-vernis', 'Vernir la porte', 'Portes & fenêtres', 'travaux', 'normale', 120, '', array['termites']::text[]);
insert into task_rooms (task_id, room_id) values ('portes-vernis', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('portes-vernis', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('portes-vernis', 'ch-solal');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('plinthes', 'Tester une peinture sur les plinthes', 'Peinture', 'test', 'normale', 60, 'Un essai dans une chambre, puis on généralise si c''est bien.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('plinthes', 'ch-liam');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('lumieres', 'Installer les lumières', 'Électricité & lumières', 'travaux', 'normale', 120, '', array['lum-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('lumieres', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('lumieres', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('lumieres', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('lumieres', 'ch-parents');
insert into task_rooms (task_id, room_id) values ('lumieres', 'bureau');
insert into task_rooms (task_id, room_id) values ('lumieres', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('lumieres', 'sdb-enfants');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('balais', 'Poser un balai de bas de porte (serpents)', 'Anti-serpents', 'travaux', 'haute', 20, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('balais', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('balais', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('balais', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('balais', 'ch-parents');
insert into task_rooms (task_id, room_id) values ('balais', 'ch-malik');
insert into task_rooms (task_id, room_id) values ('balais', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('rideaux', 'Poser les rideaux', 'Rideaux', 'travaux', 'normale', 45, '', array['rideaux-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('rideaux', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('rideaux', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('rideaux', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('rideaux', 'ch-parents');
insert into task_rooms (task_id, room_id) values ('rideaux', 'ch-malik');
insert into task_rooms (task_id, room_id) values ('rideaux', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('sdb-peinture', 'Peindre la salle de bain', 'Peinture', 'travaux', 'normale', 360, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sdb-peinture', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('sdb-peinture', 'sdb-enfants');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('sdb-finition', 'Carrelage ou autre finition : décider', 'Finitions', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sdb-finition', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('sdb-finition', 'sdb-enfants');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('porte-bureau', 'Condamner la porte entre notre chambre et le bureau', 'Portes & fenêtres', 'travaux', 'normale', 240, 'Une seule opération pour les deux pièces.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('porte-bureau', 'ch-parents');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('porte-chambre', 'Réparer la porte de la chambre qui ne ferme pas', 'Portes & fenêtres', 'travaux', 'normale', 90, 'Dictée : ''porte d''entrée''. Compris comme la porte de la chambre, à confirmer.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('porte-chambre', 'ch-parents');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('dessus-porte', 'Fermer l''ouverture au-dessus de la porte', 'Portes & fenêtres', 'travaux', 'normale', 180, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('dessus-porte', 'ch-parents');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('boiseries-dec', 'Boiseries : les exploiter ou les fondre dans le mur ?', 'Boiseries', 'decision', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('boiseries-dec', 'ch-parents');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('boiseries-parents', 'Boiseries : réaliser l''option choisie', 'Boiseries', 'travaux', 'normale', 240, '', array['boiseries-dec','termites-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('boiseries-parents', 'ch-parents');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('pf-parents', 'Peindre les portes-fenêtres', 'Portes & fenêtres', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('pf-parents', 'ch-parents');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('malik-fenetres', 'Faire les fenêtres', 'Portes & fenêtres', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('malik-fenetres', 'ch-malik');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('malik-peinture', 'Peindre la chambre', 'Peinture', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('malik-peinture', 'ch-malik');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('malik-porte', 'Finir de peindre la porte en turquoise', 'Portes & fenêtres', 'travaux', 'normale', 60, '', array['turquoise-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('malik-porte', 'ch-malik');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('malik-ventilo', 'Installer un ventilateur', 'Ventilation', 'travaux', 'normale', 120, 'Ajoute les autres pièces qui en ont besoin.', array['ventilo-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('malik-ventilo', 'ch-malik');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('bureau-rangement', 'Ranger le bureau et virer le bazar', 'Rangement', 'travaux', 'haute', 240, 'Débloque tout le reste de la pièce.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau-rangement', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('bureau-poutres', 'Combler les trous en haut des murs (poutres) : planches ou autre', 'Boiseries', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau-poutres', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('bureau-portes', 'Peindre la porte et la porte-fenêtre', 'Portes & fenêtres', 'travaux', 'normale', 180, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau-portes', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('bureau-fenetre', 'Réparer la fenêtre cassée', 'Portes & fenêtres', 'travaux', 'haute', 120, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau-fenetre', 'bureau');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('sdb-vitre', 'Poser une vitre sur la fenêtre', 'Portes & fenêtres', 'travaux', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sdb-vitre', 'sdb-parents');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('sdb-eau', 'Évacuation d''eau : stagne et déborde', 'Plomberie', 'travaux', 'urgente', 240, 'Risque de dégâts des eaux : avant toute finition.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sdb-eau', 'sdb-enfants');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('chaux-prep', 'Préparer la chaux (éteindre, laisser reposer)', 'Enduit chaux', 'travaux', 'normale', 120, 'Chaux vive = caustique : lunettes et gants.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('chaux-prep', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('chaux-reprise', 'Reprendre la chaux aux endroits cassés', 'Enduit chaux', 'travaux', 'normale', 240, '', array['chaux-prep']::text[]);
insert into task_rooms (task_id, room_id) values ('chaux-reprise', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('dalles', 'Couvrir les tranches de dalles en ciment apparent', 'Finitions', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('dalles', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('poteaux-dec', 'Poteaux : peindre ou habiller ?', 'Finitions', 'decision', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('poteaux-dec', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('poteaux', 'Poteaux : réaliser l''option choisie', 'Finitions', 'travaux', 'normale', 480, '', array['poteaux-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('poteaux', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('plancher-buanderie', 'Plancher au-dessus de la buanderie', 'Structure', 'travaux', 'normale', 960, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('plancher-buanderie', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('tiroir', 'Séparateurs dans le tiroir à couverts', 'Mobilier', 'travaux', 'basse', 15, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('tiroir', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('appliques-bar', 'Appliques au-dessus du bar', 'Électricité & lumières', 'travaux', 'normale', 120, '', array['lum-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('appliques-bar', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('lumieres-salon', 'Replacer toutes les lumières', 'Électricité & lumières', 'travaux', 'normale', 180, '', array['lum-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('lumieres-salon', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('sous-escalier', 'Meubles sous l''escalier', 'Mobilier', 'travaux', 'normale', 960, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sous-escalier', 'salon');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('appliques-couloirs', 'Poser des appliques', 'Électricité & lumières', 'travaux', 'normale', 180, '', array['lum-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('appliques-couloirs', 'couloirs');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('aile-dec', 'Autre aile : escalier ou appartement indépendant ?', 'Autre aile', 'decision', 'haute', 60, 'Préférence : appartement. Mais un escalier depuis le salon réduit l''indépendance.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('aile-dec', 'aile');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('aile-mur', 'Monter le mur de séparation', 'Autre aile', 'travaux', 'normale', 960, '', array['aile-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('aile-mur', 'aile');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('aile-terrasse', 'Ouvrir derrière : terrasse et porte-fenêtre', 'Autre aile', 'travaux', 'normale', 1920, '', array['aile-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('aile-terrasse', 'aile');
insert into tasks (id, title, lot, kind, priority, minutes, note, depends_on) values ('aile-escalier', 'Escalier : extérieur ou depuis le salon ?', 'Autre aile', 'decision', 'normale', 60, '', array['aile-dec']::text[]);
insert into task_rooms (task_id, room_id) values ('aile-escalier', 'aile');
insert into options (id, task_id, label) values ('lum-dec-o1', 'lum-dec', 'Spots encastrés');
insert into options (id, task_id, label) values ('lum-dec-o2', 'lum-dec', 'Abat-jour / suspensions');
insert into options (id, task_id, label) values ('lum-dec-o3', 'lum-dec', 'Mixte selon les pièces');
insert into options (id, task_id, label) values ('boiseries-dec-o1', 'boiseries-dec', 'Les exploiter pour suspendre des choses');
insert into options (id, task_id, label) values ('boiseries-dec-o2', 'boiseries-dec', 'Les peindre couleur mur pour les fondre');
insert into options (id, task_id, label) values ('poteaux-dec-o1', 'poteaux-dec', 'Peindre');
insert into options (id, task_id, label) values ('poteaux-dec-o2', 'poteaux-dec', 'Habiller (bois, corde, enduit…)');
insert into options (id, task_id, label) values ('aile-dec-o1', 'aile-dec', 'Escalier depuis la maison');
insert into options (id, task_id, label) values ('aile-dec-o2', 'aile-dec', 'Appartement indépendant');
insert into options (id, task_id, label) values ('aile-escalier-o1', 'aile-escalier', 'Escalier extérieur');
insert into options (id, task_id, label) values ('aile-escalier-o2', 'aile-escalier', 'Escalier depuis le salon');
insert into shopping (id, label, qty, store, task_id) values ('c-chaux', 'Chaux aérienne', '1 sac', 'Matériaux', 'enduit-essais');
insert into shopping (id, label, qty, store, task_id) values ('c-sable', 'Sable fin', '1 sac', 'Matériaux', 'enduit-essais');
insert into shopping (id, label, qty, store, task_id) values ('c-panneaux', 'Panneaux pour les essais d''enduit', '3-4', 'Bricolage', 'enduit-essais');
insert into shopping (id, label, qty, store, task_id) values ('c-balais', 'Balais de bas de porte', '6', 'Bricolage', 'balais');
insert into shopping (id, label, qty, store, task_id) values ('c-tiroir', 'Séparateurs de tiroir à couverts', '1', '', 'tiroir');
insert into shopping (id, label, qty, store, task_id) values ('c-vitre', 'Vitre sur mesure (mesurer avant)', '1', 'Vitrier', 'sdb-vitre');
commit;
