-- Généré par scripts/gen_seed.py. Ajoutez vos e-mails dans members avant (voir SETUP.md).
begin;
insert into rooms (id, name, sort) values ('maison', 'Toute la maison', 0);
insert into rooms (id, name, sort) values ('ch-liam', 'Chambre Liam', 1);
insert into rooms (id, name, sort) values ('ch-maceo', 'Chambre Maceo', 2);
insert into rooms (id, name, sort) values ('ch-solal', 'Chambre Solal', 3);
insert into rooms (id, name, sort) values ('ch-parents', 'Notre chambre', 4);
insert into rooms (id, name, sort) values ('ch-malik', 'Chambre Malik', 5);
insert into rooms (id, name, sort) values ('bureau', 'Bureau', 6);
insert into rooms (id, name, sort) values ('sdb-parents', 'Notre salle de bain', 7);
insert into rooms (id, name, sort) values ('sdb-enfants', 'SDB enfants + Malik', 8);
insert into rooms (id, name, sort) values ('salon', 'Salon / cuisine', 9);
insert into rooms (id, name, sort) values ('couloirs', 'Couloirs', 10);
insert into rooms (id, name, sort) values ('toit', 'Toit', 11);
insert into rooms (id, name, sort) values ('aile', 'Autre aile', 12);
insert into projects (id, title, priority, note, sort) values ('solaire', 'Bruit du solaire', 'urgente', 'Grande urgence.', 0);
insert into projects (id, title, priority, note, sort) values ('evacuation', 'Évacuation de la SDB enfants', 'urgente', 'L''eau stagne et déborde : risque de dégâts des eaux.', 1);
insert into projects (id, title, priority, note, sort) values ('serpents', 'Anti-serpents : balais de porte', 'haute', '', 2);
insert into projects (id, title, priority, note, sort) values ('termites', 'Traitement termites', 'haute', 'A faire avant toute peinture ou vernis sur le bois.', 3);
insert into projects (id, title, priority, note, sort) values ('eclairage', 'Éclairage', 'haute', 'La décision bloque les saignées, donc l''enduit.', 4);
insert into projects (id, title, priority, note, sort) values ('peinture', 'Peinture des chambres', 'normale', '', 5);
insert into projects (id, title, priority, note, sort) values ('enduit', 'Enduit à la chaux', 'haute', 'Une seule recherche et une seule série d''essais pour toutes les pièces.', 6);
insert into projects (id, title, priority, note, sort) values ('menuiseries', 'Portes et fenêtres : turquoise et vernis', 'normale', '', 7);
insert into projects (id, title, priority, note, sort) values ('reparations', 'Réparations portes et fenêtres', 'haute', '', 8);
insert into projects (id, title, priority, note, sort) values ('rideaux', 'Rideaux', 'normale', '', 9);
insert into projects (id, title, priority, note, sort) values ('sdb', 'Salles de bain : embellir', 'normale', '', 10);
insert into projects (id, title, priority, note, sort) values ('ventilos', 'Ventilateurs', 'normale', '', 11);
insert into projects (id, title, priority, note, sort) values ('salon-chaux', 'Salon : reprise de la chaux', 'normale', '', 12);
insert into projects (id, title, priority, note, sort) values ('poteaux', 'Salon : poteaux', 'normale', '', 13);
insert into projects (id, title, priority, note, sort) values ('dalles', 'Salon : tranches de dalles', 'normale', '', 14);
insert into projects (id, title, priority, note, sort) values ('plancher', 'Plancher au-dessus de la buanderie', 'normale', '', 15);
insert into projects (id, title, priority, note, sort) values ('bureau', 'Bureau : ranger et habiller le haut des murs', 'haute', '', 16);
insert into projects (id, title, priority, note, sort) values ('boiseries-parents', 'Notre chambre : boiseries', 'normale', '', 17);
insert into projects (id, title, priority, note, sort) values ('penderie', 'Penderie', 'normale', '', 18);
insert into projects (id, title, priority, note, sort) values ('sous-escalier', 'Meubles sous l''escalier', 'normale', '', 19);
insert into projects (id, title, priority, note, sort) values ('aile', 'Autre aile', 'normale', 'Préférence : appartement. Mais un escalier depuis le salon réduit l''indépendance.', 20);
insert into stages (id, project_id, title, kind, sort) values ('solaire.concevoir', 'solaire', 'Décider', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('solaire.acheter', 'solaire', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('solaire.construire', 'solaire', 'Fermer', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('evacuation.diag', 'evacuation', 'Diagnostiquer', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('evacuation.acheter', 'evacuation', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('evacuation.reparer', 'evacuation', 'Réparer', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('evacuation.verifier', 'evacuation', 'Vérifier', 'finir', 3);
insert into stages (id, project_id, title, kind, sort) values ('serpents.acheter', 'serpents', 'Acheter', 'acheter', 0);
insert into stages (id, project_id, title, kind, sort) values ('serpents.poser', 'serpents', 'Poser', 'appliquer', 1);
insert into stages (id, project_id, title, kind, sort) values ('termites.choisir', 'termites', 'Choisir', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('termites.acheter', 'termites', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('termites.traiter', 'termites', 'Traiter', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('eclairage.decider', 'eclairage', 'Décider', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('eclairage.acheter', 'eclairage', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('eclairage.saignees', 'eclairage', 'Saignées et câbles', 'preparer', 2);
insert into stages (id, project_id, title, kind, sort) values ('eclairage.installer', 'eclairage', 'Installer', 'appliquer', 3);
insert into stages (id, project_id, title, kind, sort) values ('peinture.choisir', 'peinture', 'Choisir', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('peinture.acheter', 'peinture', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('peinture.tester', 'peinture', 'Tester', 'tester', 2);
insert into stages (id, project_id, title, kind, sort) values ('peinture.plafonds', 'peinture', 'Plafonds', 'appliquer', 3);
insert into stages (id, project_id, title, kind, sort) values ('peinture.boiseries', 'peinture', 'Boiseries et murs', 'appliquer', 4);
insert into stages (id, project_id, title, kind, sort) values ('enduit.renseigner', 'enduit', 'Se renseigner', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('enduit.acheter', 'enduit', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('enduit.tester', 'enduit', 'Tester', 'tester', 2);
insert into stages (id, project_id, title, kind, sort) values ('enduit.preparer', 'enduit', 'Préparer les murs', 'preparer', 3);
insert into stages (id, project_id, title, kind, sort) values ('enduit.appliquer', 'enduit', 'Appliquer', 'appliquer', 4);
insert into stages (id, project_id, title, kind, sort) values ('menuiseries.choisir', 'menuiseries', 'Choisir', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('menuiseries.acheter', 'menuiseries', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('menuiseries.tester', 'menuiseries', 'Tester', 'tester', 2);
insert into stages (id, project_id, title, kind, sort) values ('menuiseries.preparer', 'menuiseries', 'Poncer', 'preparer', 3);
insert into stages (id, project_id, title, kind, sort) values ('menuiseries.appliquer', 'menuiseries', 'Peindre et vernir', 'appliquer', 4);
insert into stages (id, project_id, title, kind, sort) values ('reparations.mesurer', 'reparations', 'Mesurer', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('reparations.acheter', 'reparations', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('reparations.reparer', 'reparations', 'Réparer', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('reparations.fermer', 'reparations', 'Condamner et fermer', 'appliquer', 3);
insert into stages (id, project_id, title, kind, sort) values ('rideaux.choisir', 'rideaux', 'Choisir', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('rideaux.acheter', 'rideaux', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('rideaux.poser', 'rideaux', 'Poser', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('sdb.decider', 'sdb', 'Décider', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('sdb.acheter', 'sdb', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('sdb.peindre', 'sdb', 'Peindre', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('sdb.finitions', 'sdb', 'Finitions', 'finir', 3);
insert into stages (id, project_id, title, kind, sort) values ('ventilos.technique', 'ventilos', 'Trouver la technique', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('ventilos.acheter', 'ventilos', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('ventilos.installer', 'ventilos', 'Installer', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('salon-chaux.acheter', 'salon-chaux', 'Acheter', 'acheter', 0);
insert into stages (id, project_id, title, kind, sort) values ('salon-chaux.preparer', 'salon-chaux', 'Préparer la chaux', 'preparer', 1);
insert into stages (id, project_id, title, kind, sort) values ('salon-chaux.appliquer', 'salon-chaux', 'Reprendre', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('poteaux.decider', 'poteaux', 'Décider', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('poteaux.acheter', 'poteaux', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('poteaux.realiser', 'poteaux', 'Réaliser', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('dalles.decider', 'dalles', 'Décider', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('dalles.acheter', 'dalles', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('dalles.realiser', 'dalles', 'Réaliser', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('plancher.concevoir', 'plancher', 'Concevoir', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('plancher.acheter', 'plancher', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('plancher.construire', 'plancher', 'Construire', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('bureau.ranger', 'bureau', 'Ranger', 'preparer', 0);
insert into stages (id, project_id, title, kind, sort) values ('bureau.concevoir', 'bureau', 'Décider', 'decider', 1);
insert into stages (id, project_id, title, kind, sort) values ('bureau.acheter', 'bureau', 'Acheter', 'acheter', 2);
insert into stages (id, project_id, title, kind, sort) values ('bureau.poser', 'bureau', 'Poser', 'appliquer', 3);
insert into stages (id, project_id, title, kind, sort) values ('boiseries-parents.decider', 'boiseries-parents', 'Décider', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('boiseries-parents.realiser', 'boiseries-parents', 'Réaliser', 'appliquer', 1);
insert into stages (id, project_id, title, kind, sort) values ('penderie.concevoir', 'penderie', 'Concevoir', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('penderie.acheter', 'penderie', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('penderie.construire', 'penderie', 'Construire', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('sous-escalier.concevoir', 'sous-escalier', 'Concevoir', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('sous-escalier.acheter', 'sous-escalier', 'Acheter', 'acheter', 1);
insert into stages (id, project_id, title, kind, sort) values ('sous-escalier.construire', 'sous-escalier', 'Construire', 'appliquer', 2);
insert into stages (id, project_id, title, kind, sort) values ('aile.decider', 'aile', 'Décider', 'decider', 0);
insert into stages (id, project_id, title, kind, sort) values ('aile.travaux', 'aile', 'Gros œuvre', 'appliquer', 1);
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('solaire.1', 'Choisir comment fermer le réduit et le WC visiteurs', 'solaire', 'solaire.concevoir', 'decision', 'urgente', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('solaire.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('solaire.2', 'Acheter les matériaux (plaques, isolant…)', 'solaire', 'solaire.acheter', 'achat', 'urgente', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('solaire.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('solaire.3', 'Fermer le petit réduit', 'solaire', 'solaire.construire', 'travaux', 'urgente', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('solaire.3', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('solaire.4', 'Monter le mur des toilettes visiteurs', 'solaire', 'solaire.construire', 'travaux', 'urgente', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('solaire.4', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('evacuation.1', 'Trouver pourquoi l''eau stagne', 'evacuation', 'evacuation.diag', 'travaux', 'urgente', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('evacuation.1', 'sdb-enfants');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('evacuation.2', 'Acheter les pièces', 'evacuation', 'evacuation.acheter', 'achat', 'urgente', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('evacuation.2', 'sdb-enfants');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('evacuation.3', 'Réparer l''évacuation', 'evacuation', 'evacuation.reparer', 'travaux', 'urgente', 180, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('evacuation.3', 'sdb-enfants');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('evacuation.4', 'Vérifier après une semaine d''usage', 'evacuation', 'evacuation.verifier', 'travaux', 'urgente', 15, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('evacuation.4', 'sdb-enfants');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('serpents.1', 'Acheter les balais de bas de porte', 'serpents', 'serpents.acheter', 'achat', 'haute', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('serpents.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('serpents.2', 'Poser un balai de bas de porte', 'serpents', 'serpents.poser', 'travaux', 'haute', 20, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('serpents.2', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('serpents.2', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('serpents.2', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('serpents.2', 'ch-parents');
insert into task_rooms (task_id, room_id) values ('serpents.2', 'ch-malik');
insert into task_rooms (task_id, room_id) values ('serpents.2', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('termites.1', 'Choisir le produit et la méthode', 'termites', 'termites.choisir', 'decision', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('termites.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('termites.2', 'Acheter le produit anti-termites', 'termites', 'termites.acheter', 'achat', 'haute', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('termites.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('termites.3', 'Traiter les bois', 'termites', 'termites.traiter', 'travaux', 'haute', 60, 'Salon : la fenêtre.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('termites.3', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('termites.3', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('termites.3', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('termites.3', 'bureau');
insert into task_rooms (task_id, room_id) values ('termites.3', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('termites.3', 'sdb-enfants');
insert into task_rooms (task_id, room_id) values ('termites.3', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('termites.4', 'Traiter le haut du toit', 'termites', 'termites.traiter', 'travaux', 'haute', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('termites.4', 'toit');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('eclairage.1', 'Spots encastrés ou abat-jour ?', 'eclairage', 'eclairage.decider', 'decision', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('eclairage.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('eclairage.2', 'Acheter luminaires, câbles et boîtiers', 'eclairage', 'eclairage.acheter', 'achat', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('eclairage.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('eclairage.3', 'Saigner les murs et passer les fils', 'eclairage', 'eclairage.saignees', 'travaux', 'haute', 240, 'Avant l''enduit, sinon on casse l''enduit neuf.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('eclairage.3', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('eclairage.3', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('eclairage.3', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('eclairage.3', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('eclairage.4', 'Installer les lumières', 'eclairage', 'eclairage.installer', 'travaux', 'haute', 120, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('eclairage.4', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('eclairage.4', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('eclairage.4', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('eclairage.4', 'ch-parents');
insert into task_rooms (task_id, room_id) values ('eclairage.4', 'bureau');
insert into task_rooms (task_id, room_id) values ('eclairage.4', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('eclairage.4', 'sdb-enfants');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('eclairage.5', 'Appliques au-dessus du bar', 'eclairage', 'eclairage.installer', 'travaux', 'haute', 120, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('eclairage.5', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('eclairage.6', 'Replacer toutes les lumières du salon', 'eclairage', 'eclairage.installer', 'travaux', 'haute', 180, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('eclairage.6', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('eclairage.7', 'Poser des appliques', 'eclairage', 'eclairage.installer', 'travaux', 'haute', 180, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('eclairage.7', 'couloirs');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('peinture.1', 'Choisir peintures et couleurs', 'peinture', 'peinture.choisir', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('peinture.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('peinture.2', 'Acheter la peinture', 'peinture', 'peinture.acheter', 'achat', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('peinture.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('peinture.3', 'Tester une peinture sur les plinthes', 'peinture', 'peinture.tester', 'test', 'normale', 60, 'Un essai, puis on généralise si c''est bien.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('peinture.3', 'ch-liam');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('peinture.4', 'Peindre le plafond', 'peinture', 'peinture.plafonds', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('peinture.4', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('peinture.4', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('peinture.4', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('peinture.4', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('peinture.5', 'Peindre les boiseries', 'peinture', 'peinture.boiseries', 'travaux', 'normale', 180, '', array['termites.3']::text[]);
insert into task_rooms (task_id, room_id) values ('peinture.5', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('peinture.5', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('peinture.5', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('peinture.5', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('peinture.6', 'Peindre la chambre', 'peinture', 'peinture.boiseries', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('peinture.6', 'ch-malik');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('enduit.1', 'Se documenter : recettes, dosages, supports', 'enduit', 'enduit.renseigner', 'travaux', 'haute', 120, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('enduit.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('enduit.2', 'Acheter chaux, sable et panneaux d''essai', 'enduit', 'enduit.acheter', 'achat', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('enduit.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('enduit.3', 'Faire des essais sur panneaux', 'enduit', 'enduit.tester', 'test', 'haute', 240, 'Noter chaque essai dans le carnet : recette, photo, verdict.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('enduit.3', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('enduit.4', 'Choisir la recette', 'enduit', 'enduit.tester', 'decision', 'haute', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('enduit.4', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('enduit.5', 'Préparer les murs (reboucher, humidifier)', 'enduit', 'enduit.preparer', 'travaux', 'haute', 120, '', array['eclairage.3']::text[]);
insert into task_rooms (task_id, room_id) values ('enduit.5', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('enduit.5', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('enduit.5', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('enduit.5', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('enduit.6', 'Appliquer l''enduit', 'enduit', 'enduit.appliquer', 'travaux', 'haute', 480, '', array['peinture.4']::text[]);
insert into task_rooms (task_id, room_id) values ('enduit.6', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('enduit.6', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('enduit.6', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('enduit.6', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.1', 'Choisir le turquoise (teinte, type de peinture)', 'menuiseries', 'menuiseries.choisir', 'decision', 'normale', 45, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.2', 'Acheter peinture turquoise et vernis', 'menuiseries', 'menuiseries.acheter', 'achat', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.3', 'Tester la teinte sur un cadre', 'menuiseries', 'menuiseries.tester', 'test', 'normale', 60, 'Étape ajoutée : voir la teinte en vrai avant de tout peindre.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.3', 'ch-liam');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.4', 'Poncer et préparer', 'menuiseries', 'menuiseries.preparer', 'travaux', 'normale', 120, '', array['termites.3']::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.4', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('menuiseries.4', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('menuiseries.4', 'ch-solal');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.5', 'Peindre les fenêtres en turquoise', 'menuiseries', 'menuiseries.appliquer', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.5', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('menuiseries.5', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('menuiseries.5', 'ch-solal');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.6', 'Vernir la porte', 'menuiseries', 'menuiseries.appliquer', 'travaux', 'normale', 120, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.6', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('menuiseries.6', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('menuiseries.6', 'ch-solal');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.7', 'Finir la porte en turquoise', 'menuiseries', 'menuiseries.appliquer', 'travaux', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.7', 'ch-malik');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.8', 'Peindre les portes-fenêtres', 'menuiseries', 'menuiseries.appliquer', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.8', 'ch-parents');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('menuiseries.9', 'Peindre la porte et la porte-fenêtre', 'menuiseries', 'menuiseries.appliquer', 'travaux', 'normale', 180, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('menuiseries.9', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.1', 'Mesurer et lister ce qu''il faut', 'reparations', 'reparations.mesurer', 'travaux', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.2', 'Acheter quincaillerie et vitre', 'reparations', 'reparations.acheter', 'achat', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.3', 'Réparer la fenêtre cassée', 'reparations', 'reparations.reparer', 'travaux', 'haute', 120, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.3', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.4', 'Poser une vitre sur la fenêtre', 'reparations', 'reparations.reparer', 'travaux', 'haute', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.4', 'sdb-parents');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.5', 'Réparer la porte qui ne ferme pas', 'reparations', 'reparations.reparer', 'travaux', 'haute', 90, 'Dictée : ''porte d''entrée''. Compris comme la porte de la chambre, à confirmer.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.5', 'ch-parents');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.6', 'Régler la porte d''entrée', 'reparations', 'reparations.reparer', 'travaux', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.6', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.7', 'Faire les fenêtres', 'reparations', 'reparations.reparer', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.7', 'ch-malik');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.8', 'Condamner la porte entre notre chambre et le bureau', 'reparations', 'reparations.fermer', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.8', 'ch-parents');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('reparations.9', 'Fermer l''ouverture au-dessus de la porte', 'reparations', 'reparations.fermer', 'travaux', 'normale', 180, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('reparations.9', 'ch-parents');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('rideaux.1', 'Choisir les rideaux', 'rideaux', 'rideaux.choisir', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('rideaux.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('rideaux.2', 'Acheter les rideaux et tringles', 'rideaux', 'rideaux.acheter', 'achat', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('rideaux.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('rideaux.3', 'Poser les rideaux', 'rideaux', 'rideaux.poser', 'travaux', 'normale', 45, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('rideaux.3', 'ch-liam');
insert into task_rooms (task_id, room_id) values ('rideaux.3', 'ch-maceo');
insert into task_rooms (task_id, room_id) values ('rideaux.3', 'ch-solal');
insert into task_rooms (task_id, room_id) values ('rideaux.3', 'ch-parents');
insert into task_rooms (task_id, room_id) values ('rideaux.3', 'ch-malik');
insert into task_rooms (task_id, room_id) values ('rideaux.3', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('sdb.1', 'Carrelage ou autre finition ?', 'sdb', 'sdb.decider', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sdb.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('sdb.2', 'Acheter peinture et matériaux', 'sdb', 'sdb.acheter', 'achat', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sdb.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('sdb.3', 'Peindre la salle de bain', 'sdb', 'sdb.peindre', 'travaux', 'normale', 360, '', array['termites.3']::text[]);
insert into task_rooms (task_id, room_id) values ('sdb.3', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('sdb.3', 'sdb-enfants');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('sdb.4', 'Poser la finition choisie', 'sdb', 'sdb.finitions', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sdb.4', 'sdb-parents');
insert into task_rooms (task_id, room_id) values ('sdb.4', 'sdb-enfants');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('ventilos.1', 'Trouver comment poser un ventilateur', 'ventilos', 'ventilos.technique', 'decision', 'normale', 90, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('ventilos.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('ventilos.2', 'Acheter le(s) ventilateur(s)', 'ventilos', 'ventilos.acheter', 'achat', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('ventilos.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('ventilos.3', 'Installer un ventilateur', 'ventilos', 'ventilos.installer', 'travaux', 'normale', 120, 'Ajoute les autres pièces qui en ont besoin.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('ventilos.3', 'ch-malik');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('salon-chaux.1', 'Acheter la chaux pour le salon', 'salon-chaux', 'salon-chaux.acheter', 'achat', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('salon-chaux.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('salon-chaux.2', 'Éteindre la chaux et la laisser reposer', 'salon-chaux', 'salon-chaux.preparer', 'travaux', 'normale', 120, 'Chaux vive = caustique : lunettes et gants.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('salon-chaux.2', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('salon-chaux.3', 'Reprendre la chaux aux endroits cassés', 'salon-chaux', 'salon-chaux.appliquer', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('salon-chaux.3', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('poteaux.1', 'Poteaux : peindre ou habiller ?', 'poteaux', 'poteaux.decider', 'decision', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('poteaux.1', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('poteaux.2', 'Acheter le nécessaire', 'poteaux', 'poteaux.acheter', 'achat', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('poteaux.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('poteaux.3', 'Traiter les poteaux', 'poteaux', 'poteaux.realiser', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('poteaux.3', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('dalles.1', 'Comment couvrir le ciment apparent ?', 'dalles', 'dalles.decider', 'decision', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('dalles.1', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('dalles.2', 'Acheter le nécessaire', 'dalles', 'dalles.acheter', 'achat', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('dalles.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('dalles.3', 'Couvrir les tranches de dalles', 'dalles', 'dalles.realiser', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('dalles.3', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('plancher.1', 'Choisir la structure et le bois', 'plancher', 'plancher.concevoir', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('plancher.1', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('plancher.2', 'Acheter le bois et la visserie', 'plancher', 'plancher.acheter', 'achat', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('plancher.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('plancher.3', 'Poser le plancher', 'plancher', 'plancher.construire', 'travaux', 'normale', 960, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('plancher.3', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('bureau.1', 'Ranger le bureau et virer le bazar', 'bureau', 'bureau.ranger', 'travaux', 'haute', 240, 'Débloque tout le reste de la pièce.', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau.1', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('bureau.2', 'Combler les trous des poutres : planches ou autre ?', 'bureau', 'bureau.concevoir', 'decision', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau.2', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('bureau.3', 'Acheter les planches', 'bureau', 'bureau.acheter', 'achat', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau.3', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('bureau.4', 'Combler les trous en haut des murs', 'bureau', 'bureau.poser', 'travaux', 'normale', 480, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('bureau.4', 'bureau');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('boiseries-parents.1', 'Les exploiter ou les fondre dans le mur ?', 'boiseries-parents', 'boiseries-parents.decider', 'decision', 'normale', 30, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('boiseries-parents.1', 'ch-parents');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('boiseries-parents.2', 'Réaliser l''option choisie', 'boiseries-parents', 'boiseries-parents.realiser', 'travaux', 'normale', 240, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('boiseries-parents.2', 'ch-parents');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('penderie.1', 'Dessiner le meuble et ses dimensions', 'penderie', 'penderie.concevoir', 'decision', 'normale', 90, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('penderie.1', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('penderie.2', 'Acheter bois et quincaillerie', 'penderie', 'penderie.acheter', 'achat', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('penderie.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('penderie.3', 'Construire la penderie', 'penderie', 'penderie.construire', 'travaux', 'normale', 960, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('penderie.3', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('sous-escalier.1', 'Dessiner les meubles', 'sous-escalier', 'sous-escalier.concevoir', 'decision', 'normale', 90, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sous-escalier.1', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('sous-escalier.2', 'Acheter bois et quincaillerie', 'sous-escalier', 'sous-escalier.acheter', 'achat', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sous-escalier.2', 'maison');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('sous-escalier.3', 'Construire les meubles', 'sous-escalier', 'sous-escalier.construire', 'travaux', 'normale', 960, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('sous-escalier.3', 'salon');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('aile.1', 'Escalier ou appartement indépendant ?', 'aile', 'aile.decider', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('aile.1', 'aile');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('aile.2', 'Escalier : extérieur ou depuis le salon ?', 'aile', 'aile.decider', 'decision', 'normale', 60, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('aile.2', 'aile');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('aile.3', 'Monter le mur de séparation', 'aile', 'aile.travaux', 'travaux', 'normale', 960, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('aile.3', 'aile');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('aile.4', 'Ouvrir derrière : terrasse et porte-fenêtre', 'aile', 'aile.travaux', 'travaux', 'normale', 1920, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('aile.4', 'aile');
insert into tasks (id, title, project_id, stage_id, kind, priority, minutes, note, depends_on) values ('petit.tiroir', 'Séparateurs dans le tiroir à couverts', null, null, 'achat', 'basse', 15, '', '{}'::text[]);
insert into task_rooms (task_id, room_id) values ('petit.tiroir', 'salon');
insert into options (id, task_id, label) values ('eclairage.1.o1', 'eclairage.1', 'Spots encastrés');
insert into options (id, task_id, label) values ('eclairage.1.o2', 'eclairage.1', 'Abat-jour / suspensions');
insert into options (id, task_id, label) values ('eclairage.1.o3', 'eclairage.1', 'Mixte selon les pièces');
insert into options (id, task_id, label) values ('poteaux.1.o1', 'poteaux.1', 'Peindre');
insert into options (id, task_id, label) values ('poteaux.1.o2', 'poteaux.1', 'Habiller (bois, corde, enduit…)');
insert into options (id, task_id, label) values ('boiseries-parents.1.o1', 'boiseries-parents.1', 'Les exploiter pour suspendre des choses');
insert into options (id, task_id, label) values ('boiseries-parents.1.o2', 'boiseries-parents.1', 'Les peindre couleur mur pour les fondre');
insert into options (id, task_id, label) values ('aile.1.o1', 'aile.1', 'Escalier depuis la maison');
insert into options (id, task_id, label) values ('aile.1.o2', 'aile.1', 'Appartement indépendant');
insert into options (id, task_id, label) values ('aile.2.o1', 'aile.2', 'Escalier extérieur');
insert into options (id, task_id, label) values ('aile.2.o2', 'aile.2', 'Escalier depuis le salon');
insert into shopping (id, label, qty, store, task_id) values ('c1', 'Balais de bas de porte', '6', 'Bricolage', 'serpents.1');
insert into shopping (id, label, qty, store, task_id) values ('c2', 'Produit anti-termites', '', '', 'termites.2');
insert into shopping (id, label, qty, store, task_id) values ('c3', 'Chaux aérienne', '1 sac', 'Matériaux', 'enduit.2');
insert into shopping (id, label, qty, store, task_id) values ('c4', 'Sable fin', '1 sac', 'Matériaux', 'enduit.2');
insert into shopping (id, label, qty, store, task_id) values ('c5', 'Panneaux pour les essais', '3-4', 'Bricolage', 'enduit.2');
insert into shopping (id, label, qty, store, task_id) values ('c6', 'Vitre sur mesure (après mesure)', '1', 'Vitrier', 'reparations.2');
insert into shopping (id, label, qty, store, task_id) values ('c7', 'Chaux pour le salon', '', 'Matériaux', 'salon-chaux.1');
insert into shopping (id, label, qty, store, task_id) values ('c8', 'Séparateurs de tiroir à couverts', '1', '', 'petit.tiroir');
commit;
